# Generated by Django 4.1.7 on 2026-03-31 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placetypes', '0003_fclass_to_fclasses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='type',
            new_name='types_path_93f79d_idx',
            old_name='types_path_idx',
        ),
        migrations.RenameIndex(
            model_name='type',
            new_name='types_is_plac_fc7023_idx',
            old_name='types_is_place_type_idx',
        ),
        migrations.AlterField(
            model_name='type',
            name='fclasses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'Administrative Boundary'), ('H', 'Hydrographic'), ('L', 'Area'), ('P', 'Populated Place'), ('R', 'Road / Railroad'), ('S', 'Spot (small feature/building/farm)'), ('T', 'Hypsographic (terrain/elevation)'), ('U', 'Undersea'), ('V', 'Vegetation')], max_length=1), blank=True, help_text='GeoNames feature classes inherited from all AAT ancestor paths.', null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='type',
            index=models.Index(fields=['depth', 'is_place_type'], name='types_depth_86dfcc_idx'),
        ),
    ]
